SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) AS MONTH, count(DISTINCT o.USER_ID) as PUCHASED_USERS, ROUND(count(DISTINCT o.USER_ID)/(select count(*) FROM USER_INFO WHERE YEAR(JOINED)="2021"),1) as PUCHASED_RATIO
FROM USER_INFO as u INNER JOIN ONLINE_SALE as o 
ON u.USER_ID= o.USER_ID
WHERE YEAR(u.JOINED)="2021"
GROUP BY YEAR, MONTH
ORDER BY  YEAR, MONTH
