SELECT ED1.ID, ED1.GENOTYPE, ED2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ED1
LEFT JOIN ECOLI_DATA AS ED2
ON ED1.PARENT_ID = ED2.ID
WHERE ED1.GENOTYPE & ED2.GENOTYPE = ED2.GENOTYPE  -- 자식의 형질에 부모가 완전히 속해야 함
ORDER BY ED1.ID