SELECT YEAR(DIFFERENTIATION_DATE)as YEAR, (select MAX(SIZE_OF_COLONY) FROM ECOLI_DATA where YEAR=YEAR(DIFFERENTIATION_DATE))-SIZE_OF_COLONY as YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR(DIFFERENTIATION_DATE),YEAR_DEV;