
SELECT CONCAT("/home/grep/src/",b.BOARD_ID,"/",FILE_ID,FILE_NAME,FILE_EXT) as FILE_PATH 
FROM USED_GOODS_BOARD as b JOIN USED_GOODS_FILE as f on b.BOARD_ID = f.BOARD_ID
WHERE VIEWS =(select max(VIEWS)FROM USED_GOODS_BOARD )
ORDER BY FILE_ID DESC;